### ISSUE TITLE
Mejora del código

### ISSUE THREAD

**Issue by manuelbg7** [iesgrancapitan-entornos/2019-20-practica-5-github-issues-JaviEpi#1]
https://github.com/iesgrancapitan-entornos/2019-20-practica-5-github-issues-JaviEpi/blob/218b63cdffec0505122575c6094dc56f5a7895e0/index.html#L10

Buenas Javier, para mejorar la legibilidad del código te aconsejo que cambies la etiqueta de 'h2' a 'h1'.

`<h1>Quiero que sea un h1</h1> `

**Comment by JaviEpi** [comment]
Manuel, ya esta corregido este issues.
